apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  annotations:
    agentBareMetal-agentSelector/autoSelect: "false"
    agentBareMetal-cpuArchitecture: x86_64
  labels:
    cluster.open-cluster-management.io/clusterset: {{ .Values.cluster_set }}
    hive.openshift.io/cluster-platform: agent-baremetal
  name: {{ .Values.cluster_name }}
  namespace: {{ .Values.cluster_name }}
spec:
  preserveOnDelete: false
  baseDomain: {{ .Values.base_domain }}
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: {{ .Values.cluster_name }}
    version: v1beta1
  clusterName: {{ .Values.cluster_name }}
  platform:
    agentBareMetal:
      agentSelector: {}
  pullSecretRef:
    name: pullsecret-{{ .Values.cluster_name }}
