apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.pull_secret | b64enc }} 
kind: Secret
metadata:
  labels:
    agent-install.openshift.io/watch: "true"
    cluster.open-cluster-management.io/backup: "true"
  name: pullsecret-{{ .Values.cluster_name }}
  namespace: {{ .Values.cluster_name }}
type: kubernetes.io/dockerconfigjson
